### ISSUE TITLE
not working for me

### ISSUE THREAD

**Issue by uzairleo** [rajayogan/flutter-googlemaps#2]
i m trying to implement mapbox bcoz of billing issue but its  not working throws some exception can u plz check sir 
![image](https://user-images.githubusercontent.com/52172428/81027463-49f1a300-8e97-11ea-89cb-e316c15b68d7.png)

**Comment by rajayogan** [comment]
I think you posted this here by mistake sir. This repository is something related to google maps and flutter.

**Comment by uzairleo** [comment]
oh sorry sir. i will post it in your mapbox example hope u help
